[package]
name = "rusty_beads"
version = "0.1.0"
authors = ["Maxim Zaks <maxim.zaks@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "1.5.0"

[dev-dependencies]
csv = "1.1"